controller_manager:
  ros__parameters:
    update_rate: 10.0

    arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    gripper_controller:
      # type: joint_trajectory_controller/JointTrajectoryController
      type: forward_command_controller/ForwardCommandController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

arm_controller:
  ros__parameters:
    joints:
      - joint1
      - joint2
      - joint3

    command_interfaces:
      - position

    state_interfaces:
      - position

    open_loop_control: true
    allow_integration_in_goal_trajectories: true

gripper_controller:
  ros__parameters:
    joints:
      - joint_4

    interface_name: position

    # command_interfaces:
    #   - position

    # state_interfaces:
    #   - position

    # open_loop_control: true
    # allow_integration_in_goal_trajectories: true
